[tox]
envlist = py313, py314, lint, mypy
skip_missing_interpreters = True

[gh-actions]
python =
  3.13: py313
  3.14: py314, lint, mypy

[pytest]
asyncio_default_fixture_loop_scope=function

[testenv]
commands =
  pytest --timeout=30 --cov=openevsehttp --cov-report=xml {posargs}
deps =
  -rrequirements_test.txt

[testenv:lint]
basepython = python3
ignore_errors = True
commands =
  ruff format --check ./
  ruff check openevsehttp tests
deps =
  -rrequirements_lint.txt
  -rrequirements_test.txt

[testenv:mypy]
basepython = python3
ignore_errors = True
commands =
  mypy openevsehttp
deps =
  -rrequirements_lint.txt
